export const EVENT_TYPES = {
  // Asset lifecycle
  CREATED: 'CREATED',
  PROOF_SUBMITTED: 'PROOF_SUBMITTED',
  ATTESTATION: 'ATTESTATION',

  // Process / rental flow
  RENTAL_INITIATED: 'RENTAL_INITIATED',
  PARTICIPATION_CONFIRMED: 'PARTICIPATION_CONFIRMED',
  TERMS_ACCEPTED: 'TERMS_ACCEPTED',
  TERMS_REJECTED: 'TERMS_REJECTED',
  NEGOTIATION_EXPIRED: 'NEGOTIATION_EXPIRED',
  DEPOSIT_DECLARED: 'DEPOSIT_DECLARED',
  DEPOSIT_CONFIRMED: 'DEPOSIT_CONFIRMED',
  HANDOVER_PROOF: 'HANDOVER_PROOF',
  RETURN_PROOF: 'RETURN_PROOF',
  RETURN_VERIFIED: 'RETURN_VERIFIED',
  PROOF_VERIFIED: 'PROOF_VERIFIED',
  INCIDENT: 'INCIDENT',
  DEPOSIT_RESOLVED: 'DEPOSIT_RESOLVED',
  RESOLUTION_CONFIRMED: 'RESOLUTION_CONFIRMED',
} as const

export type EventType = (typeof EVENT_TYPES)[keyof typeof EVENT_TYPES]
