/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    assets: Asset;
    events: Event;
    templates: Template;
    processes: Process;
    'workflow-templates': WorkflowTemplate;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    assets: AssetsSelect<false> | AssetsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    processes: ProcessesSelect<false> | ProcessesSelect<true>;
    'workflow-templates': WorkflowTemplatesSelect<false> | WorkflowTemplatesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: {
      expireProcesses: TaskExpireProcesses;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  hash?: string | null;
  process?: (string | null) | Process;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Active instance of a Template applied to an Asset. Tracks the full lifecycle.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processes".
 */
export interface Process {
  id: string;
  assetId: number;
  template: string | Template;
  /**
   * Wallet address of the asset owner who initiated the process.
   */
  owner: string;
  /**
   * Role-to-wallet mapping. Every template role must be assigned an address.
   */
  participants: {
    role: string;
    address: string;
    id?: string | null;
  }[];
  status:
    | 'DRAFT'
    | 'PENDING_RENTER'
    | 'NEGOTIATING'
    | 'TERMS_AGREED'
    | 'DEPOSIT_PENDING'
    | 'DEPOSIT_CONFIRMED'
    | 'ACTIVE'
    | 'RETURN_PENDING'
    | 'RETURN_VERIFIED'
    | 'DEPOSIT_RESOLVING'
    | 'COMPLETED'
    | 'REJECTED'
    | 'EXPIRED';
  /**
   * Snapshot of the final negotiated terms.
   */
  agreedTerms?: {
    price?: number | null;
    currency?: string | null;
    duration?: number | null;
    durationUnit?: ('hours' | 'days' | 'weeks' | 'months') | null;
    deposit?: number | null;
  };
  /**
   * Whether the owner has accepted the current terms during negotiation.
   */
  ownerAccepted?: boolean | null;
  /**
   * Whether the renter has accepted the current terms during negotiation.
   */
  renterAccepted?: boolean | null;
  /**
   * Auto-set when negotiation starts. Deadline for the negotiation window.
   */
  negotiationDeadline?: string | null;
  /**
   * Set when rental becomes ACTIVE.
   */
  startDate?: string | null;
  /**
   * Computed from startDate + agreed duration when ACTIVE.
   */
  endDate?: string | null;
  /**
   * Set by owner when resolving deposit at end of rental.
   */
  depositResolution?: ('returned' | 'partial' | 'withheld') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable service blueprints (rental, lease, etc.). A Process is created from a Template.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: string;
  name: string;
  /**
   * Service type. Add more options as new services are introduced.
   */
  type: 'rental';
  description?: string | null;
  /**
   * Roles required for this process type. Each participant is assigned a role.
   */
  roles: {
    name: string;
    label: string;
    id?: string | null;
  }[];
  /**
   * Wallet address of the template author.
   */
  creator: string;
  terms: {
    price: number;
    currency?: string | null;
    duration: number;
    durationUnit: 'hours' | 'days' | 'weeks' | 'months';
    deposit: number;
    negotiable?: boolean | null;
    /**
     * Negotiation window in minutes (default 30). Only used when negotiable is true.
     */
    negotiationDuration?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets".
 */
export interface Asset {
  id: string;
  assetId: number;
  creator: string;
  /**
   * Updated from on-chain events (e.g. PROOF_SUBMITTED).
   */
  latestProofHash?: string | null;
  /**
   * URL of uploaded proof/file (from upload API).
   */
  url?: string | null;
  title?: string | null;
  description?: string | null;
  category?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable event log. On-chain events arrive via Alchemy webhook; off-chain events are created directly.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  /**
   * Free-form event type string (e.g. CREATED, PROOF_SUBMITTED, HANDOVER_PROOF, INCIDENT).
   */
  type: string;
  source: 'on-chain' | 'off-chain';
  assetId: number;
  /**
   * Payload document ID of the Process this event belongs to (optional).
   */
  processId?: string | null;
  sender: string;
  proofHash?: string | null;
  timestamp: number;
  transactionHash?: string | null;
  blockNumber?: string | null;
  /**
   * Arbitrary data for this event (negotiation terms, incident details, deposit resolution, etc.).
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Experimental workflow-driven service blueprints. Each template defines stages composed of reusable action blocks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-templates".
 */
export interface WorkflowTemplate {
  id: string;
  name: string;
  /**
   * Service type identifier (e.g. rental, lending, escrow).
   */
  type: string;
  description?: string | null;
  /**
   * Wallet address of the template author.
   */
  creator: string;
  /**
   * Roles required for this workflow. Each participant is assigned a role.
   */
  roles: {
    name: string;
    label: string;
    id?: string | null;
  }[];
  /**
   * Default terms for this service. Can be overridden during negotiation.
   */
  terms?: {
    price?: number | null;
    currency?: string | null;
    duration?: number | null;
    durationUnit?: ('hours' | 'days' | 'weeks' | 'months') | null;
    deposit?: number | null;
    negotiable?: boolean | null;
    /**
     * Negotiation window in minutes.
     */
    negotiationDuration?: number | null;
  };
  /**
   * Ordered workflow stages. Each stage defines available actions, roles, and transitions.
   */
  stages: {
    /**
     * Stage identifier used as process status (e.g. DRAFT, ACTIVE, COMPLETED).
     */
    name: string;
    /**
     * Human-readable stage name shown in the UI.
     */
    label: string;
    /**
     * Action blocks available at this stage.
     */
    actions?:
      | {
          /**
           * The action block type.
           */
          block:
            | 'confirm'
            | 'reject'
            | 'upload_proof'
            | 'verify_proof'
            | 'negotiate_terms'
            | 'accept_terms'
            | 'declare_deposit'
            | 'confirm_deposit'
            | 'resolve_deposit'
            | 'log_incident';
          /**
           * Custom button label (optional, falls back to block default).
           */
          label?: string | null;
          /**
           * Array of role names that can execute this action, e.g. ["owner", "renter"].
           */
          roles:
            | {
                [k: string]: unknown;
              }
            | unknown[]
            | string
            | number
            | boolean
            | null;
          /**
           * Event type emitted when this action is executed (e.g. DEPOSIT_DECLARED).
           */
          eventType?: string | null;
          /**
           * Stage name to transition to on success. Leave blank for non-transitioning actions.
           */
          transitionsTo?: string | null;
          /**
           * Whether this action triggers an on-chain transaction.
           */
          requiresOnChain?: boolean | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional auto-transition when time expires at this stage.
     */
    timeout?: {
      /**
       * Timeout duration.
       */
      duration?: number | null;
      unit?: ('minutes' | 'hours' | 'days') | null;
      /**
       * Stage to transition to on timeout (e.g. EXPIRED).
       */
      transitionsTo?: string | null;
    };
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'expireProcesses';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'expireProcesses') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'assets';
        value: string | Asset;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'templates';
        value: string | Template;
      } | null)
    | ({
        relationTo: 'processes';
        value: string | Process;
      } | null)
    | ({
        relationTo: 'workflow-templates';
        value: string | WorkflowTemplate;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  hash?: T;
  process?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets_select".
 */
export interface AssetsSelect<T extends boolean = true> {
  assetId?: T;
  creator?: T;
  latestProofHash?: T;
  url?: T;
  title?: T;
  description?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  type?: T;
  source?: T;
  assetId?: T;
  processId?: T;
  sender?: T;
  proofHash?: T;
  timestamp?: T;
  transactionHash?: T;
  blockNumber?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  description?: T;
  roles?:
    | T
    | {
        name?: T;
        label?: T;
        id?: T;
      };
  creator?: T;
  terms?:
    | T
    | {
        price?: T;
        currency?: T;
        duration?: T;
        durationUnit?: T;
        deposit?: T;
        negotiable?: T;
        negotiationDuration?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processes_select".
 */
export interface ProcessesSelect<T extends boolean = true> {
  assetId?: T;
  template?: T;
  owner?: T;
  participants?:
    | T
    | {
        role?: T;
        address?: T;
        id?: T;
      };
  status?: T;
  agreedTerms?:
    | T
    | {
        price?: T;
        currency?: T;
        duration?: T;
        durationUnit?: T;
        deposit?: T;
      };
  ownerAccepted?: T;
  renterAccepted?: T;
  negotiationDeadline?: T;
  startDate?: T;
  endDate?: T;
  depositResolution?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-templates_select".
 */
export interface WorkflowTemplatesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  description?: T;
  creator?: T;
  roles?:
    | T
    | {
        name?: T;
        label?: T;
        id?: T;
      };
  terms?:
    | T
    | {
        price?: T;
        currency?: T;
        duration?: T;
        durationUnit?: T;
        deposit?: T;
        negotiable?: T;
        negotiationDuration?: T;
      };
  stages?:
    | T
    | {
        name?: T;
        label?: T;
        actions?:
          | T
          | {
              block?: T;
              label?: T;
              roles?: T;
              eventType?: T;
              transitionsTo?: T;
              requiresOnChain?: T;
              id?: T;
            };
        timeout?:
          | T
          | {
              duration?: T;
              unit?: T;
              transitionsTo?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskExpireProcesses".
 */
export interface TaskExpireProcesses {
  input?: unknown;
  output: {
    expired?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}